plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

def getVersionCode = { ->
    return new Date().format("yyMMddhh", TimeZone.getTimeZone("GMT+08:00")).toInteger()
}

android {
    signingConfigs {
        mySign {
            storeFile file('D:\\littleWhiteDuck\\sign\\littleWhiteDuck.jks')
            storePassword 'littlesimpleVip'
            keyAlias 'littlewhite'
            keyPassword 'littleWhite'
        }
    }
    compileSdkVersion 31
    apply plugin: 'kotlin-kapt'
    apply plugin: 'kotlin-parcelize'
    defaultConfig {
        applicationId "me.simpleHook"
        minSdkVersion 22
        targetSdkVersion 31
        versionCode getVersionCode()
        versionName "1.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            zipAlignEnabled true
            signingConfig signingConfigs.mySign
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        viewBinding true
    }
    android.applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "simlpeHook(${variant.versionCode})_${variant.versionName}.apk"
            if (buildType.name == 'release') {
                variant.getPackageApplication().outputDirectory = new File(rootDir.absolutePath + "/app/release")
            }
        }
    }
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.6.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.preference:preference-ktx:1.1.1'
    implementation 'org.jetbrains.kotlin:kotlin-reflect:1.5.30'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    // room
    def room_version = "2.3.0"
    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"

    // xposed
    compileOnly 'de.robv.android.xposed:api:82'
    compileOnly 'de.robv.android.xposed:api:82:sources'

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.1")

    /* implementation 'androidx.navigation:navigation-fragment-ktx:2.3.0'
     implementation 'androidx.navigation:navigation-ui-ktx:2.3.0'*/

    //fab
    implementation 'com.github.clans:fab:1.6.4'

    //xPopup
    /*implementation 'com.github.li-xiaojun:XPopup:2.3.4'*/

    //悬浮窗
    implementation 'com.github.princekin-f:EasyFloat:2.0.3'

    //json
    implementation 'com.google.code.gson:gson:2.8.8'

    //splashScreen
    implementation("androidx.core:core-splashscreen:1.0.0-alpha01")
}