plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'c'
}

android {
    def normal = rootProject.ext.config.normal
    signingConfigs {
        mySign {
            storeFile file('D:\\littleWhiteDuck\\sign\\littleWhiteDuck.jks')
            storePassword 'littlesimpleVip'
            keyAlias 'littlewhite'
            keyPassword 'littleWhite'
        }
    }

    compileSdkVersion 31
    apply plugin: 'kotlin-kapt'
    apply plugin: 'kotlin-parcelize'
    defaultConfig {
        resConfigs 'zh_CN,en,zh_TW'
        applicationId "me.simpleHook"
        minSdkVersion 22
        targetSdkVersion 31
        versionCode rootProject.ext.config.versionCode
        versionName rootProject.ext.config.versionName
        flavorDimensions "default"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            zipAlignEnabled true
            signingConfig signingConfigs.mySign
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField("Boolean", "normal", "${normal}")
        }
        debug {
           // minifyEnabled true
            buildConfigField("Boolean", "normal", "${normal}")
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        viewBinding true
    }
    buildToolsVersion '31.0.0'
    android.applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "simpleHook(${variant.versionCode})_${variant.versionName}.apk"
           /* if (buildType.name == 'release') {
                variant.getPackageApplication().outputDirectory = new File(rootDir.absolutePath + "/app/release")
            }*/
        }
    }
    productFlavors {
        beta {
            versionName = rootProject.ext.config.versionName+"_beta"
           // applicationId = "me.simpleHook.beta"
        }
        public_release {
            versionName = rootProject.ext.config.versionName
        }
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.preference:preference-ktx:1.1.1'
    implementation("androidx.recyclerview:recyclerview:1.2.1")
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    // room
    def room_version = "2.4.0"
    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"

    // xposed
    compileOnly 'de.robv.android.xposed:api:82'
    compileOnly 'de.robv.android.xposed:api:82:sources'
   /* compileOnly 'com.virjar:ratel-api:1.3.5'*/

    implementation('org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.0-native-mt')

   /* def nav_version = "2.4.2"
    implementation("androidx.navigation:navigation-fragment-ktx:$nav_version")
    implementation("androidx.navigation:navigation-ui-ktx:$nav_version")*/

    //fab
//    implementation 'com.github.clans:fab:1.6.4'

    //xPopup
    /*implementation 'com.github.li-xiaojun:XPopup:2.3.4'*/

    //悬浮窗
    implementation 'com.github.princekin-f:EasyFloat:2.0.3'

    //json
    implementation 'com.google.code.gson:gson:2.9.0'

    //splashScreen
    implementation("androidx.core:core-splashscreen:1.0.0-beta01")

    //glance
    debugImplementation 'com.guolindev.glance:glance:1.1.0'

    //shell
    implementation 'com.github.d4rken:rxshell:3.0.0'

    //paging3
    def paging_version = "3.1.1"
    implementation("androidx.paging:paging-runtime:$paging_version")

    implementation("androidx.room:room-paging:2.5.0-alpha01")

    //glide

    implementation 'com.github.bumptech.glide:glide:4.13.1'
    kapt 'com.github.bumptech.glide:compiler:4.13.1'
}